name: studious_eureka
description: A demo that showcases interaction with smart contracts.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bloc: 8.0.3
  equatable: 2.0.3
  envify: 2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  flutter_web3: 2.1.9

dev_dependencies:
  build_runner: 2.1.8
  envify_generator: 2.0.2
  flutter_lints: 1.0.4
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
